name : CI Workflow for simple-api

on: 
    push:
        branches: ["master"]

env:
    DOCKER_IMAGE_NAME: simple-api
    DOCKER_REGISTRY_URL: toshiiiiiiii/prepo_shi

jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.10-slim
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with pylint
              run: |
                pylint app.py
            - name: Code coverage test
              run: pytest --cov=app --cov-report html
    build_image:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin      
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build image
              run: docker build -t $DOCKER_IMAGE_NAME:latest .
            - name: Tag image
              run: |
                docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_REGISTRY_URL:latest
            - name: Push image to repo
              run: |
                docker push $DOCKER_REGISTRY_URL:latest
    deploy_app:
          runs-on: ubuntu-latest
          needs: build_image
          steps:
            - name: AWS SSM Send-Command
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.AWS_EC2_INSTANCE_PUB }}
                key: ${{ secrets.TEST_EC2_PPK }}
                # Bash commands you want to execute
                script: |
                  docker ps -qa | xargs docker rm
                  docker run -d -p 80:5000 toshiiiiiiii/prepo_shi